# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Valyrium < Formula
  desc "OpenAI-compatible HTTP gateway that routes Chat Completions requests to Claude models via the Claude Code CLI, with MCP-relay tool calling"
  homepage "https://github.com/valyrium/valyrium"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/valyrium/valyrium/releases/download/v1.2.0/valyrium_1.2.0_darwin_amd64.tar.gz"
      sha256 "478b0bd87c07e3dcd718fd66259fb312cdc9f507bc892c111eb4ca3450e12fb1"

      define_method(:install) do
        bin.install "valyrium"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/valyrium/valyrium/releases/download/v1.2.0/valyrium_1.2.0_darwin_arm64.tar.gz"
      sha256 "71bf1f3a5cd3845c2eadd075363e3bc726c880fb1c72db43f26c9f4f2af5476e"

      define_method(:install) do
        bin.install "valyrium"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/valyrium/valyrium/releases/download/v1.2.0/valyrium_1.2.0_linux_amd64.tar.gz"
      sha256 "b84cef30287c2389c3ccbd6307641d47b44467026ecefb1da9e3de2903f68f14"
      define_method(:install) do
        bin.install "valyrium"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/valyrium/valyrium/releases/download/v1.2.0/valyrium_1.2.0_linux_arm64.tar.gz"
      sha256 "cae53d46d37c92c1b1236593b7c6797b86321795df6332f25181936320e8afbe"
      define_method(:install) do
        bin.install "valyrium"
      end
    end
  end

  service do
    run [opt_bin/"valyrium"]
    run_type :immediate
    keep_alive true
    working_dir var
    log_path var/"log/valyrium.log"
    error_log_path var/"log/valyrium.log"
    environment_variables PATH: "#{Dir.home}/.local/bin:#{Dir.home}/.claude/local:/opt/homebrew/bin:/usr/local/bin:#{std_service_path_env}"
  end

  test do
    system "#{bin}/valyrium", "--version"
  end
end
